/**
 * judge detector — offline simulation of the incoming `type: "prompt"` discipline
 * hooks (docs/TRD/discipline-judgment.md DISC-T001, DISC-B004).
 *
 * WHAT THIS IS
 *
 * Scores the prompts generated by `packages/core/hooks/prompts/build-judge-prompts.js`
 * against the corpus using the SAME text-in/verdict-out interface as the `regex`
 * detector (see `./index.js`), so `score.js` needs zero changes to run either one.
 *
 * WHICH HOOK-PROMPT(S) APPLY TO A CASE
 *
 * Production wires both `async-discipline` and `autonomy-discipline` on `Stop`
 * (`.claude/settings.json`), and `subagent-discipline` alone on `SubagentStop`. A
 * `Stop` case is therefore judged by BOTH Stop-hook prompts and counted a violation
 * if EITHER would block — this is the "any hook blocks → the stop is blocked"
 * composition every multi-hook-per-event design in this codebase assumes (and which
 * DISC-P001 is independently confirming for U1; this detector does not wait on that
 * probe landing, since "compose additively" is the only sane reading of two
 * co-registered guards and is what the harness needs regardless of which mechanism
 * turns out to enforce it). A `SubagentStop` case is judged by `subagent-discipline`
 * alone.
 *
 * HOW FAITHFULLY THIS REPRODUCES THE REAL IN-PLATFORM EVALUATOR — READ BEFORE
 * TRUSTING THE NUMBERS
 *
 * This is a simulation, not the hook. Known divergences, in descending order of how
 * much they could matter:
 *
 * 1. Response mechanism. Production's evaluator calls a `submit` tool with
 *    `{ok, reason}` (confirmed by the U2 probe, docs/modernization/probes/
 *    U2-prompt-payload.md §3). `claude --print` run as a bare subprocess has no
 *    equivalent structured-output tool available to it here, so this harness instead
 *    appends an explicit "reply with one JSON object, nothing else" instruction and
 *    parses the resulting text. The reasoning content should be equivalent; the
 *    delivery mechanism is not verified to behave identically under load or with
 *    unusual text.
 * 2. Model. Production defaults to "the small fast model" if `model` is omitted from
 *    the hook config (U2 probe, bundle-extracted field description) — an internal
 *    designation, not a published model id, and DISC-T002 (latency) is what will
 *    reveal whether the shipped hook config even gets to omit `model`. This harness
 *    pins `claude-haiku-4-5-20251001` as the closest known stand-in. If the real
 *    small-fast-model differs in judgment quality from Haiku 4.5, these scores don't
 *    transfer.
 * 3. System prompt. Production's evaluator runs under the bundle's fixed generic
 *    hook-evaluator system prompt (U2 probe §2, "You are evaluating a ${r} hook...").
 *    This harness lets `claude --print` use ITS OWN default system prompt instead,
 *    because reproducing the bundle's exact internal system prompt string was out of
 *    scope here and risks drifting further from reality than matching it approximately
 *    would fix. This is the single largest source of behavioral drift between this
 *    harness and the real hook.
 * 4. Working directory / project context. Production's evaluator is NOT told to avoid
 *    tools by policy — the bundle grants it real tool access and a transcript file to
 *    read (U2 §2, §3 agent-hook turn cap). This harness's prompts explicitly instruct
 *    "answer from the payload alone, do not use tools" (see `NO_TOOLS_BLOCK` in
 *    `build-judge-prompts.js`) for two reasons: (a) offline corpus cases have no real
 *    transcript file to read, so tool use would either fail or hallucinate one; (b) it
 *    keeps a fair, apples-to-apples comparison against `regex`, which also only ever
 *    sees `.text`. Deliberately, this harness also runs from a neutral empty
 *    directory (`os.tmpdir()`), not the repo root, so it does NOT inherit this
 *    project's own `CLAUDE.md`/`.claude/settings.json` — which would otherwise hand
 *    the judge a huge, rule-saturated context the real evaluator never sees, and
 *    would make the `self-documentation` class artificially easy.
 * 5. Payload fidelity. Corpus cases mostly lack a `payload` object (TRD §3.1.1 —
 *    `corpus.jsonl` had zero payload-bearing cases as of this task's run; see
 *    the judge's own results notes). Where absent, this detector supplies
 *    `background_tasks: [], session_crons: [], stop_hook_active: false` — i.e. "no
 *    escape valve, first pass" — which is the correct DEFAULT reading for text-only
 *    cases, but it means the escape-valve reasoning is exercised only by the one
 *    labeled `payload-dependent` case (excluded from scoring per §3.1.1) and never
 *    genuinely tested against a real non-empty `background_tasks`/`session_crons`.
 * 6. Latency is NOT comparable. `claude --print` subprocess startup alone measured
 *    ~7s baseline overhead on this machine before any judgment content is even sent —
 *    two orders of magnitude above the §6.1 A5 budget (p95 ≤ 2000ms) that governs the
 *    REAL in-hook call. Do not read per-case timings from this detector as evidence
 *    for or against A5; DISC-T002 measures that against the real hook, not this one.
 * 7. Context preamble position. When a corpus case supplies an OPTIONAL `context` field
 *    (extra situational prose a corpus author wants the judge to see — e.g. what a
 *    nearby marker or payload field would have said), this harness renders it as a
 *    labelled block PREPENDED ahead of the hook prompt's own text, sent to
 *    `claude --print` as one shot. Production's evaluator has no equivalent channel:
 *    whatever situational context it has comes from real payload fields and (per
 *    divergence #4) a real transcript file it can read via tool use, not a synthesized
 *    preamble authored after the fact. Where in the turn that information would
 *    surface, and how much weight a judge gives text sitting before the hook's own
 *    instructions versus text arriving through its normal payload/tool-read path, is
 *    therefore not verified to match. Treat `context` as an offline authoring
 *    convenience for surfacing a case's intended situation to a human or to this
 *    harness's judge, not as a faithful stand-in for how the real evaluator would learn
 *    it. Absent `context` (the common case — see TRD D7), this channel contributes
 *    nothing and the assembled prompt is byte-identical to before this field existed.
 *
 * Net: treat this detector's scores as evidence about the PROMPT's reasoning quality
 * (does the judgment logic actually work, is it correctly reasoning-based rather than
 * vocabulary-based, does it respect the self-documentation exemption), not as a
 * production-faithful preview of the shipped hook's precision/recall or latency.
 * DISC-T004 (live end-to-end) is what closes that gap.
 *
 * ERROR HANDLING
 *
 * Per TRD §6.2 ("no hook may fail a session: allow on every error path"), any
 * subprocess failure, timeout, or unparseable response is treated as `ok: true`
 * (not a violation) here too — fail open, exactly like the hooks themselves must.
 * Failures are logged to stderr (visible via `--json` is silent; plain run shows a
 * `(judge: ...)` note per failed case) rather than thrown, so one bad case doesn't
 * abort a whole `score.js` run.
 *
 * ENV
 *
 *   DISCIPLINE_JUDGE_MODEL     override the model id (default: claude-haiku-4-5-20251001)
 *   DISCIPLINE_JUDGE_TIMEOUT_MS  override the subprocess timeout (default: 60000)
 *   DISCIPLINE_JUDGE_DEBUG=1   print the resolved hook list, prompt length, and raw
 *                              response for every case to stderr
 */

'use strict';

const os = require('os');
const path = require('path');
const { spawn } = require('child_process');

const {
  buildPrompt,
  buildCombinedPrompt,
  STOP_DISCIPLINE_HOOKS,
} = require('../../../packages/core/hooks/prompts/build-judge-prompts');

const DEFAULT_MODEL = process.env.DISCIPLINE_JUDGE_MODEL || 'claude-haiku-4-5-20251001';
const DEFAULT_TIMEOUT_MS = Number(process.env.DISCIPLINE_JUDGE_TIMEOUT_MS) || 60000;
const DEBUG = process.env.DISCIPLINE_JUDGE_DEBUG === '1';

function debug(...args) {
  if (DEBUG) console.error('[judge]', ...args);
}

// Text-only offline stand-in for the real "submit tool" response contract (see
// divergence #1 in the module doc above).
const OFFLINE_RESPONSE_FORMAT = `## How to respond (offline harness — no submit tool available here)

Reply with EXACTLY ONE JSON object and nothing else — no markdown fences, no prose before
or after it:

  {"ok": true}
  {"ok": false, "reason": "<short reason, one sentence>"}`;

/**
 * Which hook prompt(s) apply to a case, by event. See module doc for the composition
 * rationale (both Stop hooks run; SubagentStop runs subagent-discipline alone).
 */
function applicableHooks(testCase) {
  if (testCase.event === 'SubagentStop') return ['subagent-discipline'];
  // Production merged the two Stop hooks into ONE prompt with two judgments
  // (2026-08-25). The detector must build what production registers, or it scores
  // prompts the platform no longer uses — measured that way it would silently
  // reproduce the pre-merge baseline and read as a clean post-merge result.
  if (testCase.event === 'Stop') return ['discipline-stop'];
  // Unknown/missing event — be conservative and check all three rather than silently
  // under-judging the case.
  return ['discipline-stop', 'subagent-discipline'];
}

/**
 * Builds the payload JSON that fills the "## Payload" / $ARGUMENTS block, from
 * whatever the corpus case supplies (TRD §3.1.1) plus safe defaults for anything it
 * doesn't. Defaults represent "no escape valve, first pass through the hook" — the
 * correct neutral reading when a case carries no payload at all.
 */
function buildPayload(testCase, hookName) {
  const p = testCase.payload || {};
  const payload = {
    hook_event_name: testCase.event || (hookName === 'subagent-discipline' ? 'SubagentStop' : 'Stop'),
    stop_hook_active: typeof p.stop_hook_active === 'boolean' ? p.stop_hook_active : false,
    background_tasks: Array.isArray(p.background_tasks) ? p.background_tasks : [],
    session_crons: Array.isArray(p.session_crons) ? p.session_crons : [],
    last_assistant_message: testCase.text,
  };
  if (hookName === 'subagent-discipline') {
    payload.agent_id = p.agent_id || testCase.id || 'offline-corpus-case';
    payload.agent_type = p.agent_type || 'unknown';
  }

  // session_id — ONLY when the case supplies one, directly or via its `context` marker.
  //
  // The Stop precondition honours "the LAST ENSEMBLE_COMMAND marker whose `session=`
  // matches this payload's `session_id`". Without a session_id in the payload NO marker
  // can ever match, so every context-bearing case falls into the precondition's
  // catch-all ("no marker matching this session -> the judgment APPLIES") and the
  // `state=none` cases score as false positives — for a harness reason, not a real one.
  //
  // Emitted conditionally rather than always, because D7 requires a case with no
  // `context` to produce a byte-identical prompt to before this channel existed. Adding
  // a key to every payload would change every case's $ARGUMENTS and break that.
  const sessionId = resolveCaseSessionId(testCase);
  if (sessionId) payload.session_id = sessionId;

  return payload;
}

/** A case's session id: explicit `session_id` wins, else parsed from its `context` marker.
 *
 * Parsing from the marker keeps the harness self-consistent by construction — the marker
 * a case carries and the payload it is judged against name the same session, which is
 * what production does. An explicit `session_id` field is honoured first so a future case
 * can deliberately MISMATCH the two and exercise the precondition's session-binding rule,
 * which parsing alone could never express.
 */
function resolveCaseSessionId(testCase) {
  const p = testCase.payload || {};
  if (typeof p.session_id === 'string' && p.session_id) return p.session_id;
  if (typeof testCase.session_id === 'string' && testCase.session_id) return testCase.session_id;
  if (typeof testCase.context !== 'string') return null;
  const m = /\bENSEMBLE_COMMAND\b[^\n]*?\bsession=([^\s]+)/.exec(testCase.context);
  return m ? m[1] : null;
}

/**
 * Renders a case's optional `context` as a labelled preamble ahead of the generated
 * hook prompt (see divergence #7 in the module doc). Returns '' when the case has no
 * `context`, which keeps the assembled prompt byte-identical to a case with no context
 * field at all (TRD D7).
 */
function buildContextPreamble(testCase) {
  if (!testCase || !testCase.context) return '';
  return `## Corpus case context (offline harness only — see divergence #7 in judge.js)\n\n${testCase.context}\n\n`;
}

/**
 * Assembles the exact text sent to `claude --print` for one (case, hook) pair —
 * the context preamble (if any), then the hook prompt with the payload substituted
 * in, then the offline response-format instruction. Exported as the seam a test can
 * use to assert on the assembled prompt without shelling out to the CLI.
 */
function buildFullPrompt(testCase, hookName) {
  const rawPrompt =
    hookName === 'discipline-stop'
      ? buildCombinedPrompt(STOP_DISCIPLINE_HOOKS)
      : buildPrompt(hookName);
  const prompt = rawPrompt.replace('$ARGUMENTS', JSON.stringify(buildPayload(testCase, hookName), null, 2));
  const contextPreamble = buildContextPreamble(testCase);
  return `${contextPreamble}${prompt}\n\n${OFFLINE_RESPONSE_FORMAT}`;
}

function extractJson(raw) {
  // Strip common markdown fencing the model may add despite instructions, then find
  // the first {...} object in the text.
  const stripped = raw.replace(/```json/gi, '```').replace(/```/g, '');
  const match = stripped.match(/\{[\s\S]*\}/);
  if (!match) return null;
  try {
    return JSON.parse(match[0]);
  } catch {
    return null;
  }
}

/**
 * Runs one hook-prompt against one case via `claude --print`. Returns a PROMISE of
 * `{ok: boolean, reason?: string}`, or of `null` on any failure (subprocess error,
 * timeout, unparseable output) — caller treats `null` as fail-open (allow).
 *
 * ASYNC SINCE 2026-09-21, and the reason is the acceptance gate itself. This used to be
 * `spawnSync`, one `claude --print` per case, strictly serial. The corpus is 86 cases and
 * `RESULTS.md:472` requires "n>=4, full corpus, every time" for BOTH the PRE and the POST
 * side of any prompt change -- ~688 serial subprocess calls to clear one edit. The harness
 * that gates every guard fix was the slowest thing in the loop it was gating.
 *
 * `score.js` already declared `detect()` awaitable, so nothing in the detector contract had
 * to change; only this function and `detect` below became genuinely asynchronous.
 */
function judgeOneHook(testCase, hookName) {
  const fullPrompt = buildFullPrompt(testCase, hookName);
  const id = testCase.id || '(no id)';

  debug(`case=${id} hook=${hookName} prompt_chars=${fullPrompt.length}`);

  return new Promise((resolve) => {
    let settled = false;
    const finish = (value) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      resolve(value);
    };

    const child = spawn('claude', ['--print', '--model', DEFAULT_MODEL], {
      cwd: os.tmpdir(), // deliberately NOT the repo root -- see divergence #4 in module doc
    });

    // SIGKILL rather than the default SIGTERM: spawnSync's `timeout` killed the process
    // outright, and a judge call that has hung is not going to clean up gracefully.
    const timer = setTimeout(() => {
      child.kill('SIGKILL');
      debug(`case=${id} hook=${hookName} timeout after ${DEFAULT_TIMEOUT_MS}ms -- fail open`);
      finish(null);
    }, DEFAULT_TIMEOUT_MS);

    let stdout = '';
    let stderr = '';
    child.stdout.setEncoding('utf-8');
    child.stderr.setEncoding('utf-8');
    child.stdout.on('data', (d) => { stdout += d; });
    child.stderr.on('data', (d) => { stderr += d; });

    child.on('error', (err) => {
      debug(`case=${id} hook=${hookName} subprocess error: ${err.message}`);
      finish(null);
    });

    child.on('close', (code) => {
      if (settled) return;
      if (code !== 0) {
        debug(`case=${id} hook=${hookName} exit ${code}: ${(stderr || '').slice(0, 200)}`);
        return finish(null);
      }
      debug(`case=${id} hook=${hookName} raw="${(stdout || '').trim().slice(0, 200)}"`);
      const parsed = extractJson(stdout || '');
      if (!parsed || typeof parsed.ok !== 'boolean') {
        debug(`case=${id} hook=${hookName} unparseable response -- fail open`);
        return finish(null);
      }
      finish(parsed);
    });

    // The child can exit before consuming stdin (bad flag, auth failure); an unhandled
    // EPIPE here would take the whole scoring run down instead of failing this one case open.
    child.stdin.on('error', () => {});
    child.stdin.end(fullPrompt);
  });
}

module.exports = {
  name: 'judge',
  description:
    'Offline simulation of the type:"prompt" discipline-hook judgments (DISC-T001) — see divergence notes in judge.js for how faithfully this reproduces production.',
  /**
   * @param {Object} testCase — corpus case; uses `.text`, `.event`, `.payload`, `.id`
   * @returns {Promise<boolean>} true if ANY applicable hook-prompt would block (violation)
   */
  async detect(testCase) {
    const hooks = applicableHooks(testCase);
    // Hooks for ONE case stay sequential: the first block short-circuits, and a case
    // applies to at most two hooks. The parallelism that matters is across cases, and
    // score.js owns it.
    for (const hookName of hooks) {
      const verdict = await judgeOneHook(testCase, hookName);
      // null (error/timeout/unparseable) fails open — treated as "this hook allows".
      if (verdict && verdict.ok === false) {
        debug(`case=${testCase.id || '(no id)'} BLOCKED by ${hookName}: ${verdict.reason || '(no reason)'}`);
        return true;
      }
    }
    return false;
  },
  // Test seam (AJCS-B001): exposes prompt assembly without shelling out to the CLI, so
  // Jest can assert on the assembled text directly. Not part of the {name, description,
  // detect} contract score.js depends on — additive only.
  applicableHooks,
  buildFullPrompt,
};
