/**
 * sweep.js test suite — wiring, not model judgement.
 *
 * The defect this command exists to remove: an owner's 25-issue list went into /create-trd,
 * ran 22.7 minutes, was killed, and four ad-hoc subagents then fixed the batch in ~13
 * minutes with no grounding and no record. These tests pin the properties that make the fast
 * path safe — parallel across regions, serial inside one, and nothing large slipping through
 * dressed as a quick win.
 */

'use strict';

const { readScript, runWorkflow, makeAgentStub, makeParallelStub } = require('./test-harness');

const SOURCE = readScript('sweep.js');

const ISSUES = [
  { id: '12', summary: 'confirmation copy missing e-sign notice', region: 'web/confirm' },
  { id: '18', summary: 'screening form gives no post-submit feedback', region: 'web/screening' },
  { id: '20', summary: 'rate box too small to type into', region: 'web/offer' },
];

function plan({ triage, fixes = {} } = {}) {
  return (prompt, opts) => {
    if (opts.label === 'triage') return triage;
    const m = /^fix:(.+)$/.exec(String(opts.label));
    if (m) {
      const id = m[1];
      if (Object.prototype.hasOwnProperty.call(fixes, id)) return fixes[id];
      return { id, status: 'fixed', summary: `fixed ${id}`, files_changed: [`src/${id}.ts`], verified: 'jest — 3 passed' };
    }
    return undefined;
  };
}

async function sweep(opts, args = { source: 'a list of issues' }) {
  const agent = makeAgentStub(plan(opts));
  const parallel = makeParallelStub();
  const { result, phases, logs } = await runWorkflow(SOURCE, { agent, parallel, args });
  return { result, phases, logs, agent, parallel };
}

const fixCalls = (agent) => agent.calls.filter((c) => String(c.opts.label).startsWith('fix:'));

describe('sweep', () => {
  it('triages before touching anything', async () => {
    const { phases } = await sweep({ triage: { fix: ISSUES, deferred: [] } });
    expect(phases).toEqual(['Triage', 'Fix']);
  });

  it('shows triage the issue list verbatim', async () => {
    // The reporter's own words are the source; paraphrasing them upstream is how a symptom
    // turns into someone's guess at a cause.
    const { agent } = await sweep(
      { triage: { fix: ISSUES, deferred: [] } },
      { source: 'the rate box is too small AND should be prepopulated' }
    );
    expect(agent.calls[0].prompt).toContain('the rate box is too small AND should be prepopulated');
  });

  it('runs separate regions in parallel', async () => {
    const { parallel } = await sweep({ triage: { fix: ISSUES, deferred: [] } });
    expect(parallel.waves).toHaveLength(1);
    expect(parallel.waves[0].size).toBe(3); // three regions, one thunk each
  });

  it('runs issues in the SAME region one after another', async () => {
    // Two agents editing one file is a lost update that raises no error. Same region is the
    // cheap stand-in for "probably the same file", decided before any grounding exists.
    const sameRegion = [
      { id: 'a', summary: 'first', region: 'web/offer' },
      { id: 'b', summary: 'second', region: 'web/offer' },
    ];
    const { parallel, agent } = await sweep({ triage: { fix: sameRegion, deferred: [] } });
    expect(parallel.waves[0].size).toBe(1); // one region => one thunk
    expect(fixCalls(agent).map((c) => c.opts.label)).toEqual(['fix:a', 'fix:b']);
  });

  it('never dispatches what triage deferred', async () => {
    const { result, agent } = await sweep({
      triage: {
        fix: [ISSUES[0]],
        deferred: [{ summary: 'move offer letter to a new template engine', why: 'too large — a design change' }],
      },
    });
    expect(fixCalls(agent)).toHaveLength(1);
    expect(result.deferred).toHaveLength(1);
    expect(result.readout).toContain('DEFERRED AT TRIAGE');
  });

  it('stops early, and says where to go, when nothing is a quick win', async () => {
    const { result, agent } = await sweep({
      triage: { fix: [], deferred: [{ summary: 'redesign onboarding', why: 'too large' }] },
    });
    expect(fixCalls(agent)).toHaveLength(0);
    expect(result.readout).toContain('nothing to fix');
    expect(result.readout).toContain('/create-prd');
  });

  it('lets a fixer that has READ the code overrule triage', async () => {
    // Triage judged from issue text alone. The fixer is the first to see the code, so its
    // "this is not small" outranks the guess — a half-finished large change is the worst
    // outcome available.
    const { result } = await sweep({
      triage: { fix: ISSUES, deferred: [] },
      fixes: { 20: { id: '20', status: 'too-big', summary: 'rate box', detail: 'the field is generated by a shared schema used in 9 places' } },
    });
    expect(result.too_big).toHaveLength(1);
    expect(result.fixed).toHaveLength(2);
    expect(result.readout).toContain('NOT A QUICK WIN');
  });

  it('reports "already fixed" as its own outcome, not as a fix', async () => {
    const { result } = await sweep({
      triage: { fix: ISSUES, deferred: [] },
      fixes: { 18: { id: '18', status: 'already-fixed', summary: 'present on this branch already' } },
    });
    expect(result.fixed).toHaveLength(2);
    expect(result.already_fixed).toHaveLength(1);
    expect(result.readout).toContain('ALREADY FIXED');
  });

  it('records a dead agent as failed rather than silently dropping the issue', async () => {
    const { result } = await sweep({
      triage: { fix: ISSUES, deferred: [] },
      fixes: { 12: undefined },
    });
    expect(result.failed).toHaveLength(1);
    expect(result.failed[0].id).toBe('12');
    expect(result.readout).toContain('FAILED');
  });

  it('carries changed files out, so they can be checked against disk', async () => {
    const { result } = await sweep({ triage: { fix: [ISSUES[0]], deferred: [] } });
    expect(result.fixed[0].files_changed).toEqual(['src/12.ts']);
    expect(result.readout).toContain('NOT COMMITTED');
  });

  it('dispatches every region even past the parallel cap', async () => {
    // The defect this pins, measured 2026-09-25 in run wf_2d45cee7-f89: the script sliced the
    // region list at its cap, put the remainder in a variable, logged that it "will run after
    // the first N" -- and never referenced that variable again. 7 issues went in, 6 fixers ran,
    // and the run reported 0 failed / 0 deferred. The 11 tests in this file all passed while
    // that was live, because none of them used more regions than the cap.
    const many = Array.from({ length: 23 }, (_, i) => ({
      id: `I${i}`, summary: `issue ${i}`, region: `area/${i}`,
    }));
    const { result, parallel } = await sweep({ triage: { fix: many, deferred: [] } });
    expect(result.fixed).toHaveLength(23);
    expect(result.regions).toBe(23);
    // 23 regions at a cap of 20 is two waves, and neither may exceed the cap.
    expect(parallel.waves.map((w) => w.size)).toEqual([20, 3]);
  });

  it('throws rather than reporting a run where a triaged issue produced no result', async () => {
    // Belt on the above: if a future dispatch change loses an issue again, the run must fail
    // loudly instead of returning a tally that looks complete.
    const agent = makeAgentStub(plan({ triage: { fix: ISSUES, deferred: [] } }));
    // A parallel stub that drops the last thunk -- simulating exactly the old truncation bug.
    const lossy = async (thunks) => Promise.all(thunks.slice(0, -1).map((t) => t()));
    lossy.waves = [];
    await expect(
      runWorkflow(SOURCE, { agent, parallel: lossy, args: { source: 'a list' } })
    ).rejects.toThrow(/never produced a result/);
  });

  it('refuses to run without an issue list', async () => {
    const agent = makeAgentStub(plan({ triage: { fix: [], deferred: [] } }));
    await expect(runWorkflow(SOURCE, { agent, parallel: makeParallelStub(), args: {} }))
      .rejects.toThrow(/source is required/);
  });
});
