/**
 * sweep.js test suite — wiring, not model judgement.
 *
 * The defect this command exists to remove: an owner's 25-issue list went into /create-trd,
 * ran 22.7 minutes, was killed, and four ad-hoc subagents then fixed the batch in ~13
 * minutes with no grounding and no record. These tests pin the properties that make the fast
 * path safe — parallel across regions, serial inside one, and nothing large slipping through
 * dressed as a quick win.
 */

'use strict';

const { readScript, runWorkflow, makeAgentStub, makeParallelStub, unpinnedLabels } = require('./test-harness');

const SOURCE = readScript('sweep.js');

const ISSUES = [
  { id: '12', summary: 'confirmation copy missing e-sign notice', region: 'web/confirm' },
  { id: '18', summary: 'screening form gives no post-submit feedback', region: 'web/screening' },
  { id: '20', summary: 'rate box too small to type into', region: 'web/offer' },
];

function plan({ triage, fixes = {} } = {}) {
  return (prompt, opts) => {
    if (opts.label === 'triage') return triage;
    const m = /^fix:(.+)$/.exec(String(opts.label));
    if (m) {
      const id = m[1];
      if (Object.prototype.hasOwnProperty.call(fixes, id)) return fixes[id];
      return { id, status: 'fixed', summary: `fixed ${id}`, files_changed: [`src/${id}.ts`], verified: 'jest — 3 passed' };
    }
    return undefined;
  };
}

async function sweep(opts, args = { source: 'a list of issues' }) {
  const agent = makeAgentStub(plan(opts));
  const parallel = makeParallelStub();
  const { result, phases, logs } = await runWorkflow(SOURCE, { agent, parallel, args });
  return { result, phases, logs, agent, parallel };
}

const fixCalls = (agent) => agent.calls.filter((c) => String(c.opts.label).startsWith('fix:'));

describe('sweep', () => {
  it('triages before touching anything', async () => {
    const { phases } = await sweep({ triage: { fix: ISSUES, deferred: [] } });
    expect(phases).toEqual(['Triage', 'Fix']);
  });

  it('shows triage the issue list verbatim', async () => {
    // The reporter's own words are the source; paraphrasing them upstream is how a symptom
    // turns into someone's guess at a cause.
    const { agent } = await sweep(
      { triage: { fix: ISSUES, deferred: [] } },
      { source: 'the rate box is too small AND should be prepopulated' }
    );
    expect(agent.calls[0].prompt).toContain('the rate box is too small AND should be prepopulated');
  });

  it('runs separate regions in parallel', async () => {
    const { parallel } = await sweep({ triage: { fix: ISSUES, deferred: [] } });
    expect(parallel.waves).toHaveLength(1);
    expect(parallel.waves[0].size).toBe(3); // three regions, one thunk each
  });

  it('runs issues in the SAME region one after another', async () => {
    // Two agents editing one file is a lost update that raises no error. Same region is the
    // cheap stand-in for "probably the same file", decided before any grounding exists.
    const sameRegion = [
      { id: 'a', summary: 'first', region: 'web/offer' },
      { id: 'b', summary: 'second', region: 'web/offer' },
    ];
    const { parallel, agent } = await sweep({ triage: { fix: sameRegion, deferred: [] } });
    expect(parallel.waves[0].size).toBe(1); // one region => one thunk
    expect(fixCalls(agent).map((c) => c.opts.label)).toEqual(['fix:a', 'fix:b']);
  });

  it('never dispatches what triage deferred', async () => {
    const { result, agent } = await sweep({
      triage: {
        fix: [ISSUES[0]],
        deferred: [{ summary: 'move offer letter to a new template engine', why: 'too large — a design change' }],
      },
    });
    expect(fixCalls(agent)).toHaveLength(1);
    expect(result.deferred).toHaveLength(1);
    expect(result.readout).toContain('DEFERRED AT TRIAGE');
  });

  it('stops early, and says where to go, when nothing is a quick win', async () => {
    const { result, agent } = await sweep({
      triage: { fix: [], deferred: [{ summary: 'redesign onboarding', why: 'too large' }] },
    });
    expect(fixCalls(agent)).toHaveLength(0);
    expect(result.readout).toContain('nothing to fix');
    expect(result.readout).toContain('/create-prd');
  });

  it('lets a fixer that has READ the code overrule triage', async () => {
    // Triage judged from issue text alone. The fixer is the first to see the code, so its
    // "this is not small" outranks the guess — a half-finished large change is the worst
    // outcome available.
    const { result } = await sweep({
      triage: { fix: ISSUES, deferred: [] },
      fixes: { 20: { id: '20', status: 'too-big', summary: 'rate box', detail: 'the field is generated by a shared schema used in 9 places' } },
    });
    expect(result.too_big).toHaveLength(1);
    expect(result.fixed).toHaveLength(2);
    expect(result.readout).toContain('NOT A QUICK WIN');
  });

  it('reports "already fixed" as its own outcome, not as a fix', async () => {
    const { result } = await sweep({
      triage: { fix: ISSUES, deferred: [] },
      fixes: { 18: { id: '18', status: 'already-fixed', summary: 'present on this branch already' } },
    });
    expect(result.fixed).toHaveLength(2);
    expect(result.already_fixed).toHaveLength(1);
    expect(result.readout).toContain('ALREADY FIXED');
  });

  it('records a dead agent as failed rather than silently dropping the issue', async () => {
    const { result } = await sweep({
      triage: { fix: ISSUES, deferred: [] },
      fixes: { 12: undefined },
    });
    expect(result.failed).toHaveLength(1);
    expect(result.failed[0].id).toBe('12');
    expect(result.readout).toContain('FAILED');
  });

  it('carries changed files out, so they can be checked against disk', async () => {
    const { result } = await sweep({ triage: { fix: [ISSUES[0]], deferred: [] } });
    expect(result.fixed[0].files_changed).toEqual(['src/12.ts']);
    expect(result.readout).toContain('NOT COMMITTED');
  });

  it('dispatches every region even past the parallel cap', async () => {
    // The defect this pins, measured 2026-09-25 in run wf_2d45cee7-f89: the script sliced the
    // region list at its cap, put the remainder in a variable, logged that it "will run after
    // the first N" -- and never referenced that variable again. 7 issues went in, 6 fixers ran,
    // and the run reported 0 failed / 0 deferred. The 11 tests in this file all passed while
    // that was live, because none of them used more regions than the cap.
    const many = Array.from({ length: 23 }, (_, i) => ({
      id: `I${i}`, summary: `issue ${i}`, region: `area/${i}`,
    }));
    const { result, parallel } = await sweep({ triage: { fix: many, deferred: [] } });
    expect(result.fixed).toHaveLength(23);
    expect(result.regions).toBe(23);
    // 23 regions at a cap of 20 is two waves, and neither may exceed the cap.
    expect(parallel.waves.map((w) => w.size)).toEqual([20, 3]);
  });

  it('throws rather than reporting a run where a triaged issue produced no result', async () => {
    // Belt on the above: if a future dispatch change loses an issue again, the run must fail
    // loudly instead of returning a tally that looks complete.
    const agent = makeAgentStub(plan({ triage: { fix: ISSUES, deferred: [] } }));
    // A parallel stub that drops the last thunk -- simulating exactly the old truncation bug.
    const lossy = async (thunks) => Promise.all(thunks.slice(0, -1).map((t) => t()));
    lossy.waves = [];
    await expect(
      runWorkflow(SOURCE, { agent, parallel: lossy, args: { source: 'a list' } })
    ).rejects.toThrow(/never produced a result/);
  });

  it('accounts for a fix whose agent invented its own id', async () => {
    // Regression, measured 2026-09-26. Agents write the schema's `id` freely: a run dispatched
    // issues "1", "2" and "3" and got back "ISSUE-1-verification-md-preflight",
    // "ISSUE-2-env-preflight-relocation" and "issue-3-promoteToTrd-unimplementable-row". The
    // accounting check compared triage's ids against those, matched none, and threw "never
    // produced a result" over three fixes that had completed and landed on disk -- so the run
    // reported `failed` and its readout was discarded.
    //
    // Every other test here missed it because `plan()`'s stub echoes the dispatched id back,
    // which makes it more obedient than any real agent. This one deliberately does not.
    const renaming = (prompt, opts) => {
      if (opts.label === 'triage') return { fix: ISSUES, deferred: [] };
      const m = /^fix:(.+)$/.exec(String(opts.label));
      if (!m) return undefined;
      return {
        id: `ISSUE-${m[1]}-a-name-the-agent-liked-better`,
        status: 'fixed',
        summary: `fixed ${m[1]}`,
        files_changed: [`src/${m[1]}.ts`],
        verified: 'jest — 3 passed',
      };
    };
    const { result } = await runWorkflow(SOURCE, {
      agent: makeAgentStub(renaming),
      parallel: makeParallelStub(),
      args: { source: 'a list' },
    });
    // The dispatched ids survive, so the accounting check is satisfied and the readout is kept.
    expect(result.fixed.map((r) => r.id).sort()).toEqual(['12', '18', '20']);
  });

  it('refuses to run without an issue list', async () => {
    const agent = makeAgentStub(plan({ triage: { fix: [], deferred: [] } }));
    await expect(runWorkflow(SOURCE, { agent, parallel: makeParallelStub(), args: {} }))
      .rejects.toThrow(/source is required/);
  });

  it('gives every agent() call an explicit agentType or model — none may inherit the session model', async () => {
    // Extends audit-trd.test.js's "gives every agent an explicit agentType" pattern
    // (packages/core/workflows/audit-trd.test.js:70-75) to this file's two call sites:
    // triage and fix:<id>.
    const { agent } = await sweep({ triage: { fix: ISSUES, deferred: [] } });
    expect(agent.calls.length).toBeGreaterThan(0);
    const unpinned = unpinnedLabels(agent);
    expect(unpinned).toEqual([]);
  });

  it('routes each fix to the specialist implementer its issue keywords match, not always backend-implementer', async () => {
    // Regression for the reported defect: every fixer was dispatched as backend-implementer
    // regardless of the issue's area. This mirrors lib/agent-routing.js's KEYWORD_TABLE
    // (agent-routing.js is the source of truth; agent-routing.test.js pins it there) since a
    // workflow script cannot require() it.
    const mixedIssues = [
      { id: '1', summary: 'rate box styling is misaligned in the React component', region: 'web/offer' },
      { id: '2', summary: 'Docker deploy to k8s fails on the workers image', region: 'infra' },
      { id: '3', summary: 'confirmation email API endpoint returns a 500', region: 'api' },
    ];
    const { agent } = await sweep(
      { triage: { fix: mixedIssues, deferred: [] } },
      { source: 'three issues' }
    );
    const byId = (id) => fixCalls(agent).find((c) => c.opts.label === `fix:${id}`);
    expect(byId('1').opts.agentType).toBe('frontend-implementer');
    expect(byId('2').opts.agentType).toBe('devops-engineer');
    expect(byId('3').opts.agentType).toBe('backend-implementer');
  });

  describe('never-unattended fragments (plan-sweep-chain)', () => {
    it('names the fragments to triage and requires a touching item to be deferred', async () => {
      const { agent } = await sweep(
        { triage: { fix: ISSUES, deferred: [] } },
        { source: 'a list', fragments: ['auth', 'migrations'] }
      );
      const prompt = agent.calls[0].prompt;
      expect(prompt).toContain('NEVER-UNATTENDED PATHS');
      expect(prompt).toContain('auth, migrations');
      expect(prompt).toMatch(/touch[^.]*MUST go in `deferred`/);
    });

    it('tells every fixer to stop with too-big when its fix would touch a fragment', async () => {
      const { agent } = await sweep(
        { triage: { fix: ISSUES, deferred: [] } },
        { source: 'a list', fragments: ['auth'] }
      );
      const fixes = fixCalls(agent);
      expect(fixes).toHaveLength(3);
      for (const c of fixes) {
        expect(c.prompt).toContain('NEVER-UNATTENDED PATHS');
        expect(c.prompt).toMatch(/too-big/);
      }
    });

    it('leaves both prompts unchanged without fragments', async () => {
      for (const extra of [{}, { fragments: [] }]) {
        const { agent } = await sweep(
          { triage: { fix: ISSUES, deferred: [] } },
          { source: 'a list', ...extra }
        );
        expect(agent.calls[0].prompt).not.toContain('NEVER-UNATTENDED');
        for (const c of fixCalls(agent)) expect(c.prompt).not.toContain('NEVER-UNATTENDED');
      }
    });
  });

  describe('criterion ids (plan-from-spec)', () => {
    const SWEEP_FILE = [
      '# Sweep: Lane', '', '**Source spec**: docs/roadmap.md § Lane', '**Core TRD**: none', '',
      '## Acceptance criteria', '',
      '- **AC-4.1** · Label reads Sign in.', '- **AC-4.2** · Rate box is wider.', '',
      '**Regression guards:**', '', '- **RG-4.1:** Onboarding is unchanged.', '',
    ].join('\n');

    it('requires each criterion id as the item id, in fix and deferred, and leaves guards out', async () => {
      const { agent, result } = await sweep(
        { triage: { fix: [{ id: 'AC-4.1', summary: 'label', region: 'web' }], deferred: [{ id: 'AC-4.2', summary: 'rate', why: 'too large' }] } },
        { source: SWEEP_FILE }
      );
      const prompt = agent.calls[0].prompt;
      expect(prompt).toContain('CRITERION IDS: AC-4.1, AC-4.2');
      expect(prompt).not.toMatch(/CRITERION IDS:[^\n]*RG-4\.1/);
      expect(result.criterion_ids).toEqual(['AC-4.1', 'AC-4.2']);
      expect(result.deferred[0].id).toBe('AC-4.2');
      const deferredProps = agent.calls[0].opts.schema.properties.deferred.items.properties;
      expect(deferredProps.id).toBeDefined();
    });

    it('is unchanged for a list without criterion ids', async () => {
      const { agent, result } = await sweep({ triage: { fix: ISSUES, deferred: [] } });
      expect(agent.calls[0].prompt).not.toContain('CRITERION IDS');
      expect(result.criterion_ids).toEqual([]);
    });
  });
});
